### ISSUE TITLE
test install instructions

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/geospatial-workshop#12]
I tested out the install instructions for "Option A: Local Installation" on June 12, 2018. I'm running mac osX 10.11.13. I already had R (version 3.4.1 (2017-06-30) and RStudio (Version 1.0.153) installed and did not update them. 

A few notes about things that may need more explaining: 
- [ ] I used [Kyng Chaos’s pre-built package](http://www.kyngchaos.com/software/frameworks) to install GDAL Complete. We should add a note here that learners will need to double-click the cardboard box icon to complete the install. Depending on their security settings, they may also get an error message about "unidentified developers". If so, they will need to go to their Security and Privacy menu and allow the GDAL Complete package.
- [ ] The instructions for installing the needed R packages says "to install them from the R prompt, type", but if learners have never used R before, it won't be clear to them what this means. I think the best way around this is to dedicate the first 20-30 minutes of the workshop to checking everyone's install and having plenty of helpers to troubleshoot. We should add this to the Instructor Notes. 
- [x] I notice we're still using the development version of ggplot2. The ggplot2 website lists June 25th as their official target date. Based on the current status of the lessons, I think we'll be ready to release in the first week of July. Making a mental note to check whether ggplot2 has released by then and to update this instruction if so.

When I installed the dev version of ggplot2, I got the following output:

![screen shot 2018-06-12 at 3 02 06 pm](https://user-images.githubusercontent.com/19176319/41319692-973a03ea-6e51-11e8-899b-f97102e6af38.png)

I'm not sure yet whether these "non-zero exit status" warnings are going to prevent me from doing any part of the lessons (I'll be working through the lessons soon), but this is something that learners will probably be concerned about if they notice it, so we should add a note here telling them whether they should worry if they see warnings. 

I will be working through the lessons and will update this issue if I run into any problems with my installs.

**Comment by ErinBecker** [comment]
On my first attempt to re-build the site, I get this error: 

![screen shot 2018-06-12 at 3 22 11 pm](https://user-images.githubusercontent.com/19176319/41320389-757f9b54-6e54-11e8-8d4f-635bb591dc14.png)

It appears that `rgdal` and `sf` did not install correctly after all. I will troubleshoot and update this comment when I figure out what happened.

**Comment by ErinBecker** [comment]
I just installed the newest version of R and RStudio and then re-tried installing `rgdal` and `sf` through the RStudio interface (I tried this also before and it didn't work with my old versions). This time they both installed with no problem. So it appears that learners do really need to have recent versions of R and RStudio and I shouldn't have skipped that step! 👍

**Comment by chris-prener** [comment]
Glad you got the install working correctly @ErinBecker - I can take care of the first checkbox re Kyng Chaos’s pre-built package to install GDAL Complete. I'll also keep an eye out on the ggplot2 release and update those instructions then.

Where are the Instructor Notes located?

**Comment by lwasser** [comment]
For the second checkbox @ErinBecker  you could be more explicit wtih the language and use this screenshot - http://www.datacarpentry.org/r-intro-geospatial/01-rstudio-intro/ of rstudio to point out hte console. then use the language:

```
To install a package in R Studio do the following
1. Open R Studio
2. Type into the console - install.packages("package-name-here")
```

Or something like that. thoughts?

**Comment by lwasser** [comment]
agreed!

**Comment by ErinBecker** [comment]
Working on this now.
