### ISSUE TITLE
add description of data

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/geospatial-workshop#2]
The workshop homepage needs a description of the data files that will be used in the workshop. This should include: 

1) A short description that can go in the "Data" callout box on the workshop homepage (index.md). Examples from other Data Carpentry workshops are shown below.

![screen shot 2018-07-12 at 10 25 25 am](https://user-images.githubusercontent.com/19176319/42649313-3b5500d2-85be-11e8-8f39-551b13115ac9.png)
![screen shot 2018-07-12 at 10 25 41 am](https://user-images.githubusercontent.com/19176319/42649320-3d62457e-85be-11e8-82e9-3577fca57d48.png)

and 2) a longer description of the data, including a description of each data file and the type of data included in that file. Examples from other DC workshops are linked below:

[Social Sciences data description](http://datacarpentry.org/socialsci-workshop/data/)
[Ecology data description](http://datacarpentry.org/ecology-workshop/data/)
[Genomics data description](https://datacarpentry.org/organization-genomics/data/)

I don't feel that I'm familiar enough with the data to be able to write this data description. However, I'd be happy to take any text that the original lesson developers can put together and do the formatting/PR work to get that text up on the page. @lwasser - do you have a data description put together somewhere that you can give me? Is there anyone else who could help put this together? We are T-7days to publication. :-)

**Comment by lwasser** [comment]
so you're looking for something on the data and about NEON @ErinBecker ??

**Comment by ErinBecker** [comment]
Something that describes the dataset well enough for learners who aren't already familiar with that sampling site to understand. It would be good to have that for each sampling site and for each type of data.

**Comment by lwasser** [comment]
i bet Megan could help with this part? for some reason her gh handle isn't coming up. i don't have that off hand. 

There is a bit on the old landing pages. things have moved around on their site so i do'nt know where everything is anymore

https://www.neonscience.org/raster-data-r
Raster data: 
These remote sensing data files provide information on the vegetation at the National Ecological Observatory Network's San Joaquin Experimental Range and Soaproot Saddle field sites. The entire dataset can be accessed by request from the NEON Data Portal.

i know you prob want more than that... maybe someone can start a template and i can help write parts once that is started?

**Comment by lwasser** [comment]
there are field site pages on neon's site too

https://www.neonscience.org/field-sites/field-sites-map/SJER
https://www.neonscience.org/field-sites/field-sites-map/SOAP

**Comment by ErinBecker** [comment]
Thanks @lwasser, this is a good start. I'll start looking at this and post a draft for review and editing. Pinging @mjones01 also in case she has any resources to add.

**Comment by ErinBecker** [comment]
Closed with #17
