### ISSUE TITLE
a python lesson?

### ISSUE THREAD

**Issue by raybellwaves** [datacarpentry/geospatial-workshop#26]
Hi all,

Any thoughts on developing a python lesson? 
Not sure if this conversation belongs here or https://carpentries.topicbox.com/groups/curriculum-geospatial?

**Comment by ErinBecker** [comment]
Hi @raybellwaves - sorry for the very delayed response on this. That conversation would be best to had on the topicbox you mentioned. I know there are others who are very interested in a Python lesson (e.g. @laufers, @tyson-swetnam), but I don't know how far those conversations have progressed. I am going to close this comment, as we don't want to bifurcate the conversation from the topicbox list.
