### ISSUE TITLE
Provide general overview of workshop organization

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/geospatial-workshop#28]
It would be useful to provide more guidance on how to organize the 2 days of the workshop based on the learners' skills. Are the full 3 lessons taught? If the audience is already familiar with R and geospatial data, is there enough material to do 2 days with the r-raster-vector lesson? If so, then what can be cut out when the other 2 lessons are taught? If not, what else should be taught?

**Comment by ErinBecker** [comment]
These can go in the Instructor Notes (https://github.com/datacarpentry/geospatial-workshop/issues/25). I have slides about this that I can adapt to markdown and add to the lesson.
