### ISSUE TITLE
Correct `docker run` syntax in setup.md file

### ISSUE THREAD

**Issue by karlbenedict** [datacarpentry/geospatial-workshop#39]
There are a couple of issues with the current `docker run` syntax provided in the setup.md file. 

1. a missing `-v` flag preceding the volume mapping from the user's local system to the container's file system, and
2. a missing, now required, `-e PASSWORD=` environment variable that sets the password for the container. Current versions of the rocker/rstudio and rocker/geospatial *will not* start unless a non-default (i.e. something other than  "rstudio") password is supplied. 

These issues are addressed in PR #38

**Comment by chris-prener** [comment]
Thanks @karlbenedict - these look great. Will accept the PR and close.
