### ISSUE TITLE
suggestions submitted via email for instructor training

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/geospatial-workshop#44]
Geospatial Workshop Overview
I'm wondering if this section would better serve as an episode to Introduction to Geospatial Concepts?

About Raster Data
"This includes the raster's extent and cell size, the number of rows and columns, and its coordinate reference system (or CRS). " could benefit from the same link offered at the bottom of the page (under Raster Data Format for this Workshop):
3. Coordinate Reference System (CRS) - we will introduce this concept in a later episode

Multi-band Raster Data

Perhaps some information could be helpful here regarding how raster bands can sometimes be stored as layers together in one raster dataset, or bands can be stored separately and can be stacked/layered by the user.

Introduction to Geospatial Raster and Vector Data with R
- I think it's tricky to see from the episode list which ones discuss vector data. I like how these are split up into two separate lessons on the NEON site.

**Comment by chris-prener** [comment]
Just so I understand @ErinBecker - the suggestion from instructor training would be to combine the current geospatial concepts lesson into the overall workshop "lesson"?

**Comment by ErinBecker** [comment]
I think the suggestion was to remove the workshop overview page and instead have that information as the first episode in the geospatial concepts lesson. I would advise against this for a couple of reasons,

a) All of the DC curricula have a workshop overview page to orient the Instructors and learners, and to provide overall information for people who are thinking about requesting the workshop and

b) The geospatial concepts lesson is optional. 

I would recommend closing this issue. :-)

**Comment by chris-prener** [comment]
Gotcha. Yeah - I like that we have an overview page... I concur on closing this!
