### ISSUE TITLE
Gdal install link broken

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/geospatial-workshop#45]
GDAL install link broken in table [here](https://datacarpentry.org/geospatial-workshop/setup.html), maybe it should be to [here](https://gdal.org/download.html) instead?

**Comment by chris-prener** [comment]
Thanks @sstevens2 - I'll get this fixed!

**Comment by annefou** [comment]
Maybe we should review the installation of such tools. for instance using conda (conda install -c conda-forge gdal).  What do you think?

**Comment by sstevens2** [comment]
I was planning on making an issue about that too actually.  I find the install instructions to be very complicated.  They send you to pages where it isn't obvious which link is the best one to download from.  I *think* I got the software install but I'm not even 100% sure at the moment.  I may have more specific instructions after we teach the workshop here this Thurs/Friday.

**Comment by annefou** [comment]
Excellent. The only platform I won't be able to test is Mac-OSX but I guess you have a mac so we could review the setup procedures and then test it on different OS!
Thanks for you feedback and good luck with the workshop!

**Comment by chris-prener** [comment]
Whatever feedback you have would be great! That first table with the broken link is modeled on other Data Carpentry lessons. My own person opinion is that the table is distracting, most users shouldn't need to install GDAL from the link in the first table - the instructions below are the most relevant pieces.

I'd be happy to add Conda instructions along side what we already have below as well, but am not a Conda user. If you want to either open a PR or give me the syntax, I can add it!

**Comment by sstevens2** [comment]
You beat me to this message... I think the table should be removed or put into a call out or something. I saw it first and then didn't get to the quick instructions below I think.

**Comment by sstevens2** [comment]
I think for the gdal, geos, and proj.4 section for mac.  It needs to be more obvious that you can use the prebuilt package instead of using the home brew commands.  I saw those first when I opened it.  Though I not been reading carefully enough I guess either.  Maybe putting those in a callout within the callout for macos that is titled "homebrew option"?  I also think step by step bullet points for the first part might make it easier for those like myself who aren't reading carefully.  1. Download this file (FYI it includes some other libraries as well) 2. Follow install instructions..btw you might have to right click to open. 

Apologies for the brevity or lack of clarity in this message.  Workshop tomorrow. :-D

**Comment by chris-prener** [comment]
Good luck with the workshop @sstevens2 - let me know how it goes! 

I really appreciate your feedback- I think your suggestion is great - I'm going to make some proposed changes after I'm back in the states (am at useR! 2019 right now). I've seen this page increasingly cited (both in twitter and here at useR!) outside of Data Carpentry contexts as a guide for getting up and running with rspatial, so I think making it as user friendly as possible is really key for our various constituents. I'll keep you posted.

**Comment by chris-prener** [comment]
@sstevens2 - there are now "Beginner" and "Advanced" versions in the instructions... if you (or anyone else) has better ideas for what to call them, feel free to open a new issue!
