### ISSUE TITLE
Installation:  GDAL via Homebrew error

### ISSUE THREAD

**Issue by kerchner** [datacarpentry/geospatial-workshop#47]
Following the Mac instructions on https://github.com/datacarpentry/geospatial-workshop/blob/8c4603f6ffb2f2dfe83481ecf64c66dc76f667ca/setup.md and opting for the Homebrew / command-line installation, executing

`brew install gdal2 --with-armadillo --with-complete --with-libkml --with-unsupported`

yields the following error:

`Error: invalid option: --with-armadillo`

While I did find various github and stackoverflow threads about this issue, many of them required fiddling with one's version of Xcode, CLT, etc.   That's going to be way over the heads of most Carpentries participants simply looking to get set up.

If someone can come up with, or find, a simple fix to this instruction line that should work for most users, then great.

If not, the current layout of the instruction
![image](https://user-images.githubusercontent.com/3451175/62554484-34374a80-b83f-11e9-91e0-441100337d85.png)
might be reconsidered to draw people's attention to the `.pkg` install, which is less likely to have problems, rather than the command-line install.   Granted, the command-line install is a more tailored installation and avoids installing unnecessary packages, but I think with Carpentries we want to make this as accessible as possible and direct people to the most straightforward installation.   Perhaps provide a link out to the Homebrew installation ("for advanced users"), but remove it from this instruction.

For what it's worth, here's my current `brew config`:

```$ brew config
HOMEBREW_VERSION: 2.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3dab11263c7d3ae568bd585932b393ef526fc5b2
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a00f7dd1dadd7f1d36669a65325c8cd10c24bdc5
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497```

**Comment by chris-prener** [comment]
Thanks for the feedback @kerchner - I'm going to put this on my todo list- I think your approach to label home-brew as an advanced approach makes a whole lot of sense!

**Comment by kerchner** [comment]
@chris-prener Should I submit a PR with the wording change?   Or wait until there's a solution for the error using the `--with-armadillo` flag?

**Comment by chris-prener** [comment]
thanks for offering a PR @kerchner - I'd happily accept a PR if you can make one!

**Comment by chris-prener** [comment]
Hi @kerchner - I removed the flags after poking around a bit - seems like it should install as needed without them. Simplified instructions have been folded into the `setup.md` file!

**Comment by kerchner** [comment]
@chris-prener Outstanding.  Glad you were able to fix it by removing the flags, and I very much 👍 the way you separated out beginner vs. advanced.  Looks great!
