### ISSUE TITLE
typo in contributing.md file

### ISSUE THREAD

**Issue by tautme** [datacarpentry/geospatial-workshop#48]
There is a typo "and and" in the sentence portion below.

...updating or filling in the documentation and and submitting bug reports...

**Comment by annefou** [comment]
Indeed! Would you like to submit a pull request to fix it?

**Comment by tautme** [comment]
I could try that out, never done before.

**Comment by annefou** [comment]
Great! And let us know if you need help.

Thank you.

**Comment by tautme** [comment]
Thanks for the push to try it out. 

Let me know if I did it correctly and any constructive criticism.

**Comment by jsta** [comment]
Looks like the same typo is in the template contributing file: https://github.com/carpentries/workshop-template

Could you (@tautme) open a pull request there as well?

**Comment by tautme** [comment]
Thanks @jsta and @annefou 
I need some help.
I am attempting to open the next pull request from the command line. 
Here is my attempt.

git clone git@github.com:carpentries/workshop-template.git
cd workshop-template
git branch typo
git checkout typo

Then go into CONTRIBUTION.md and make edit

git add CONTRIBUTION.md
git commit -m "make a typo correction, and and"
git push

**Comment by annefou** [comment]
Hi @tautme, from the command line, the first step is to fork the repository and then you clone your "forked" repository and not https://github.com/datacarpentry/geospatial-workshop

To fork the repository go to https://github.com/datacarpentry/geospatial-workshop and click on "fork" (top right). More on fork at https://help.github.com/en/articles/fork-a-repo on how to fork

And if you struggle, we can have a slack or short google hangout/zoom/skype if it helps.

**Comment by tautme** [comment]
@annefou A short chat on zoom would be helpful. I think I have branch off of my fork edited, but I have not created a pull request from it yet. I also need to get rid of the first pull request I made to the master.

**Comment by chris-prener** [comment]
Hey @tautme - I just merged your PR on this - thanks for submitting it!
