### ISSUE TITLE
Lesson Contribution for Check Out

### ISSUE THREAD

**Issue by RobertBrowder** [datacarpentry/geospatial-workshop#60]
For this lesson: https://datacarpentry.org/geospatial-workshop/

Under the Data header, please see paragraph 3, sentence 1, which currently reads:

"These data files represent teaching version of the data, with sufficient complexity to teach many aspects of data analysis and management, but with many complexities removed to allow students to focus on the core ideas and skills being taught."

Please consider updating to:

"These data files represent _the_ teaching version of the data"...

**Comment by jsta** [comment]
Thanks @RobertBrowder
