### ISSUE TITLE
Some small punctuation additions to dataset descriptions.

### ISSUE THREAD

**Issue by jer-azz** [datacarpentry/geospatial-workshop#62]
Dataset descriptions #2 & #4 - some punctuation:

Dataset 2: Meteorological data. I added a full stop at the end of the sentence. "Precipitation, temperature and other variables collected from a flux tower at the NEON Harvard Forest site."

Dataset 4: Landstat 7 NDVI raster data. I added a comma and a full stop. "2011 NDVI data product derived from Landsat 7 and processed by USGS, cropped to NEON’s Harvard Forest and San Joaquin Experimental Range field sites."

**Comment by likeajumprope** [comment]
Closing this issue as the PRs have been merged.
